export const ERC_20_WITH_PERMIT_AND_FAUCET_ABI = [
  { type: "error", inputs: [], name: "ECDSAInvalidSignature" },
  {
    type: "error",
    inputs: [
      {
        name: "length",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "ECDSAInvalidSignatureLength",
  },
  {
    type: "error",
    inputs: [
      {
        name: "s",
        type: "bytes32",
        baseType: "bytes32",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "ECDSAInvalidSignatureS",
  },
  {
    type: "error",
    inputs: [
      {
        name: "spender",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "allowance",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "needed",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "ERC20InsufficientAllowance",
  },
  {
    type: "error",
    inputs: [
      {
        name: "sender",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "balance",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "needed",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "ERC20InsufficientBalance",
  },
  {
    type: "error",
    inputs: [
      {
        name: "approver",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "ERC20InvalidApprover",
  },
  {
    type: "error",
    inputs: [
      {
        name: "receiver",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "ERC20InvalidReceiver",
  },
  {
    type: "error",
    inputs: [
      {
        name: "sender",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "ERC20InvalidSender",
  },
  {
    type: "error",
    inputs: [
      {
        name: "spender",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "ERC20InvalidSpender",
  },
  {
    type: "error",
    inputs: [
      {
        name: "deadline",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "ERC2612ExpiredSignature",
  },
  {
    type: "error",
    inputs: [
      {
        name: "signer",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "owner",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "ERC2612InvalidSigner",
  },
  {
    type: "error",
    inputs: [
      {
        name: "account",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "currentNonce",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "InvalidAccountNonce",
  },
  { type: "error", inputs: [], name: "InvalidShortString" },
  {
    type: "error",
    inputs: [
      {
        name: "str",
        type: "string",
        baseType: "string",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "StringTooLong",
  },
  {
    type: "event",
    inputs: [
      {
        name: "owner",
        type: "address",
        baseType: "address",
        indexed: true,
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "spender",
        type: "address",
        baseType: "address",
        indexed: true,
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "value",
        type: "uint256",
        baseType: "uint256",
        indexed: false,
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "Approval",
    anonymous: false,
  },
  { type: "event", inputs: [], name: "EIP712DomainChanged", anonymous: false },
  {
    type: "event",
    inputs: [
      {
        name: "from",
        type: "address",
        baseType: "address",
        indexed: true,
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "to",
        type: "address",
        baseType: "address",
        indexed: true,
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "value",
        type: "uint256",
        baseType: "uint256",
        indexed: false,
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "Transfer",
    anonymous: false,
  },
  {
    type: "function",
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    constant: true,
    outputs: [
      {
        name: "",
        type: "bytes32",
        baseType: "bytes32",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    stateMutability: "view",
    payable: false,
  },
  {
    type: "function",
    inputs: [
      {
        name: "owner",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "spender",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "allowance",
    constant: true,
    outputs: [
      {
        name: "",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    stateMutability: "view",
    payable: false,
  },
  {
    type: "function",
    inputs: [
      {
        name: "spender",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "value",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "approve",
    constant: false,
    outputs: [
      {
        name: "",
        type: "bool",
        baseType: "bool",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    stateMutability: "nonpayable",
    payable: false,
  },
  {
    type: "function",
    inputs: [
      {
        name: "account",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "balanceOf",
    constant: true,
    outputs: [
      {
        name: "",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    stateMutability: "view",
    payable: false,
  },
  {
    type: "function",
    inputs: [],
    name: "decimals",
    constant: true,
    outputs: [
      {
        name: "",
        type: "uint8",
        baseType: "uint8",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    stateMutability: "view",
    payable: false,
  },
  {
    type: "function",
    inputs: [],
    name: "eip712Domain",
    constant: true,
    outputs: [
      {
        name: "fields",
        type: "bytes1",
        baseType: "bytes1",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "name",
        type: "string",
        baseType: "string",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "version",
        type: "string",
        baseType: "string",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "chainId",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "verifyingContract",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "salt",
        type: "bytes32",
        baseType: "bytes32",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "extensions",
        type: "uint256[]",
        baseType: "array",
        components: null,
        arrayLength: -1,
        arrayChildren: {
          name: "",
          type: "uint256",
          baseType: "uint256",
          components: null,
          arrayLength: null,
          arrayChildren: null,
        },
      },
    ],
    stateMutability: "view",
    payable: false,
  },
  {
    type: "function",
    inputs: [
      {
        name: "recepient",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "amount",
        type: "uint240",
        baseType: "uint240",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "faucet",
    constant: false,
    outputs: [],
    stateMutability: "nonpayable",
    payable: false,
  },
  {
    type: "function",
    inputs: [],
    name: "name",
    constant: true,
    outputs: [
      {
        name: "",
        type: "string",
        baseType: "string",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    stateMutability: "view",
    payable: false,
  },
  {
    type: "function",
    inputs: [
      {
        name: "owner",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "nonces",
    constant: true,
    outputs: [
      {
        name: "",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    stateMutability: "view",
    payable: false,
  },
  {
    type: "function",
    inputs: [
      {
        name: "owner",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "spender",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "value",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "deadline",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "v",
        type: "uint8",
        baseType: "uint8",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "r",
        type: "bytes32",
        baseType: "bytes32",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "s",
        type: "bytes32",
        baseType: "bytes32",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "permit",
    constant: false,
    outputs: [],
    stateMutability: "nonpayable",
    payable: false,
  },
  {
    type: "function",
    inputs: [],
    name: "symbol",
    constant: true,
    outputs: [
      {
        name: "",
        type: "string",
        baseType: "string",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    stateMutability: "view",
    payable: false,
  },
  {
    type: "function",
    inputs: [],
    name: "totalSupply",
    constant: true,
    outputs: [
      {
        name: "",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    stateMutability: "view",
    payable: false,
  },
  {
    type: "function",
    inputs: [
      {
        name: "to",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "value",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "transfer",
    constant: false,
    outputs: [
      {
        name: "",
        type: "bool",
        baseType: "bool",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    stateMutability: "nonpayable",
    payable: false,
  },
  {
    type: "function",
    inputs: [
      {
        name: "from",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "to",
        type: "address",
        baseType: "address",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
      {
        name: "value",
        type: "uint256",
        baseType: "uint256",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    name: "transferFrom",
    constant: false,
    outputs: [
      {
        name: "",
        type: "bool",
        baseType: "bool",
        components: null,
        arrayLength: null,
        arrayChildren: null,
      },
    ],
    stateMutability: "nonpayable",
    payable: false,
  },
] as const;
