name: Quality Gate

on:
  push:

  workflow_dispatch:

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_and_validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Code quality
        run: npm run lint
      - name: Build validation
        env:
          NODE_ENV: production
        run: npm run build
